# Version of docker-compose.
version: "3.8"

# Containers we're going to run.
services:
   # Our Phoenix container.
   app:
      # The build parameters for this container.
      build:
         # Here we define that it should build from the current directory.
         context: .
      environment:
         # Variables to connect to our Redis.
         REDIS_URI: "redis://redis:6379"
      ports:
         # Mapping the port to make the Phoenix app accessible outside of the container.
         - '4000:4000'
      depends_on:
         # The redis container needs to be started before we start this container.
         - redis
   redis:
      image: "redis:latest"
      restart: always
      ports:
         - '6379:6379'
      volumes: 
         - cache:/data
volumes:
  cache:
    driver: local